server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:/tls/skvazy.p12
    key-store-password: ${TLS_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: skvazy
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  application:
    name: cms-core
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect
jwt_secret_key: ${JWT_SECRET_KEY}
